### ISSUE TITLE
deduplicate_images报错

### ISSUE THREAD

**Issue by kuugaoggy** [WSH032/image-deduplicate-cluster-webui#2]
Traceback (most recent call last):
  File "D:\image-deduplicate-cluster-webui-main\deduplicate_images.py", line 417, in <module>
    delet_button.click(fn=delet,
  File "D:\image-deduplicate-cluster-webui-main\venv\lib\site-packages\gradio\events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "D:\image-deduplicate-cluster-webui-main\venv\lib\site-packages\gradio\blocks.py", line 237, in set_event_trigger
    special_args(fn) if fn else (None, None, None)
  File "D:\image-deduplicate-cluster-webui-main\venv\lib\site-packages\gradio\helpers.py", line 631, in special_args
    elif type_hint and issubclass(type_hint, EventData):
TypeError: issubclass() arg 1 must be a class

**Comment by WSH032** [comment]
收到，能告诉我是怎么触发这个错误的吗？
是在按下删除按钮的时候吗？
python版本大于3.9吗？gradio版本是多少呢？

**Comment by WSH032** [comment]
昨天有个一模一样的问题，我们可以移到那边去讨论
https://github.com/WSH032/image-deduplicate-cluster-webui/issues/1
